#!/usr/bin/ash
#
# SPDX-License-Identifier: GPL-3.0-or-later

run_hook() {
    if [ -n "$(getarg 'ip')" ] && [ -n "$(getarg 'lingmo_http_srv')" ]; then

        # booting with http is always copy-to-ram, so set here to make sure
        # addresses are flushed and interface is set down
        export copytoram="y"

        lingmo_http_srv=$(eval echo "${lingmo_http_srv}")
        lingmo_http_spc="$(getarg 'lingmo_http_spc' '75%')"

        export mount_handler="lingmo_pxe_http_mount_handler"
    fi
}

# Fetch a file with CURL
#
# $1 URL
# $2 Destination directory inside httpspace/${lingmo_boot}
_curl_get() {
    local _url="${1}"
    local _dst="${2}"

    msg ":: Downloading '${_url}'"
    # shellcheck disable=SC2154
    # defined in lingmo hook
    if ! curl -L -f -o "/run/lingmo/httpspace/${lingmo_boot}${_dst}/${_url##*/}" --create-dirs "${_url}"; then
        echo "ERROR: Downloading '${_url}'"
        echo "   Falling back to interactive prompt"
        echo "   You can try to fix the problem manually, log out when you are finished"
        launch_interactive_shell
    fi
}

lingmo_pxe_http_mount_handler() {
    newroot="${1}"
    local img_type="sfs"

    msg ":: Mounting /run/lingmo/httpspace (tmpfs) filesystem, size='${lingmo_http_spc}'"
    mount --mkdir -t tmpfs -o size="${lingmo_http_spc}",mode=0755 httpspace "/run/lingmo/httpspace"

    # shellcheck disable=SC2154
    # defined in lingmo hook
    if ! curl -L -f -o /dev/null -s -r 0-0 "${lingmo_http_srv}${lingmo_boot}/${arch}/lingmosys.sfs"; then
        if curl -L -f -o /dev/null -s -r 0-0 "${lingmo_http_srv}${lingmo_boot}/${arch}/lingmosys.erofs"; then
            img_type="erofs"
        fi
    fi
    _curl_get "${lingmo_http_srv}${lingmo_boot}/${arch}/lingmosys.${img_type}" "/${arch}"

    if [ "$(getarg 'checksum')" = "y" ]; then
        _curl_get "${lingmo_http_srv}${lingmo_boot}/${arch}/lingmosys.sha512" "/${arch}"
    fi
    if [ "$(getarg 'verify')" = "y" ]; then
        _curl_get "${lingmo_http_srv}${lingmo_boot}/${arch}/lingmosys.${img_type}.sig" "/${arch}"
    fi
    if [ "$(getarg 'cms_verify')" = "y" ]; then
        _curl_get "${lingmo_http_srv}${lingmo_boot}/${arch}/lingmosys.${img_type}.cms.sig" "/${arch}"
    fi

    mount --mkdir -o bind /run/lingmo/httpspace /run/lingmo/bootmnt

    lingmo_mount_handler "${newroot}"
}

# vim: set ft=sh:
